export const SCHEDULER = {

  // Block sizing
  BLOCK_CEILING_COLD_START_MINS: 60,
  BLOCK_CEILING_MAX_MINS: 90,
  BLOCK_CEILING_MIN_MINS: 60,
  BLOCK_FLOOR_MINS: 25,
  BLOCK_INCREMENT_MINS: 10,

  // Cold start cap on target_block_mins
  COLD_START_BLOCK_CAP_MINS: 45,

  // Confidence-adjusted block sizing multipliers
  CONFIDENCE_FULL_THRESHOLD: 0.75,
  CONFIDENCE_PARTIAL_THRESHOLD: 0.40,
  CONFIDENCE_PARTIAL_MULTIPLIER: 0.75,
  CONFIDENCE_LOW_MULTIPLIER: 0.50,

  // Spacing
  SPACING_PENALTY: 0.15,
  STABILITY_BONUS: 0.10,

  // Shallow blocks
  SHALLOW_BATCH_MAX_TASKS: 3,
  SHALLOW_BATCH_MAX_MINS: 25,
  SHALLOW_DEEP_GAP_MINS: 15,

  // Placement scoring weights (normal mode)
  PLACEMENT_URGENCY_WEIGHT: 0.5,
  PLACEMENT_DEMAND_WEIGHT: 0.5,

  // Placement scoring weights (urgency mode)
  URGENCY_MODE_URGENCY_WEIGHT: 1.0,
  URGENCY_MODE_DEMAND_WEIGHT: 0.0,

  // Urgency threshold bounds
  URGENCY_THRESHOLD_COLD_START: 2.0,
  URGENCY_THRESHOLD_FLOOR: 1.5,
  URGENCY_THRESHOLD_CEILING: 3.0,

  // Early anchor
  EARLY_ANCHOR_FRACTION: 0.33,

  // Max deep blocks per day by profile stage (indexed by stage 1/2/3)
  MAX_DEEP_BLOCKS_PER_DAY: [0, 2, 3, 4] as const,

  // Profile stage thresholds
  STAGE_2_REFLECTION_THRESHOLD: 5,
  STAGE_3_REFLECTION_THRESHOLD: 12,

  // Ceiling adjustment
  CEILING_RAISE_SESSION_COUNT: 5,
  CEILING_LOWER_SESSION_COUNT: 4,
  CEILING_RAISE_COMPLETION_THRESHOLD: 0.80,
  CEILING_LOWER_COMPLETION_THRESHOLD: 0.50,
  CEILING_RAISE_QUALITY_THRESHOLD: 3.5,
  CEILING_LOWER_QUALITY_THRESHOLD: 2.5,
  CEILING_ADJUST_COOLDOWN_DAYS: 7,

  // Profile update weights by stage
  STAGE_2_NEW_WEIGHT: 0.1,
  STAGE_2_CURRENT_WEIGHT: 0.9,
  STAGE_3_NEW_WEIGHT: 0.3,
  STAGE_3_CURRENT_WEIGHT: 0.7,

  // Peak hour map — faster memory than other dimensions
  PEAK_HOUR_STAGE_3_NEW_WEIGHT: 0.4,
  PEAK_HOUR_STAGE_3_CURRENT_WEIGHT: 0.6,

  // Cold start profile update
  COLD_START_COMPLETION_CONFIRM_THRESHOLD: 0.80,
  COLD_START_QUALITY_CONFIRM_THRESHOLD: 3.5,
  COLD_START_COMPLETION_RETAIN_THRESHOLD: 0.50,

} as const
